<?php
/**
 * CreateZonePushTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateZonePushTest Class Doc Comment
 *
 * @category    Class
 * @description CreateZonePush
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateZonePushTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateZonePush"
     */
    public function testCreateZonePush()
    {
    }

    /**
     * Test attribute "_method"
     */
    public function testPropertyMethod()
    {
    }

    /**
     * Test attribute "server"
     */
    public function testPropertyServer()
    {
    }

    /**
     * Test attribute "cnames"
     */
    public function testPropertyCnames()
    {
    }

    /**
     * Test attribute "cache_cache"
     */
    public function testPropertyCacheCache()
    {
    }

    /**
     * Test attribute "edge"
     */
    public function testPropertyEdge()
    {
    }

    /**
     * Test attribute "domainlock"
     */
    public function testPropertyDomainlock()
    {
    }

    /**
     * Test attribute "securetoken"
     */
    public function testPropertySecuretoken()
    {
    }

    /**
     * Test attribute "ssl"
     */
    public function testPropertySsl()
    {
    }
}
