<?php
/**
 * PostMultiBitratePushTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PostMultiBitratePushTest Class Doc Comment
 *
 * @category    Class
 * @description PostMultiBitratePush
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostMultiBitratePushTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PostMultiBitratePush"
     */
    public function testPostMultiBitratePush()
    {
    }

    /**
     * Test attribute "_method"
     */
    public function testPropertyMethod()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "server"
     */
    public function testPropertyServer()
    {
    }

    /**
     * Test attribute "audioonly"
     */
    public function testPropertyAudioonly()
    {
    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {
    }

    /**
     * Test attribute "parentid"
     */
    public function testPropertyParentid()
    {
    }

    /**
     * Test attribute "ssl"
     */
    public function testPropertySsl()
    {
    }

    /**
     * Test attribute "abr"
     */
    public function testPropertyAbr()
    {
    }

    /**
     * Test attribute "domainlock"
     */
    public function testPropertyDomainlock()
    {
    }

    /**
     * Test attribute "geoblock"
     */
    public function testPropertyGeoblock()
    {
    }

    /**
     * Test attribute "rtmpauth"
     */
    public function testPropertyRtmpauth()
    {
    }

    /**
     * Test attribute "eac"
     */
    public function testPropertyEac()
    {
    }
}
