<?php
/**
 * StreamTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StreamTest Class Doc Comment
 *
 * @category    Class
 * @description Stream
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StreamTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Stream"
     */
    public function testStream()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "serviceid"
     */
    public function testPropertyServiceid()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "audioonly"
     */
    public function testPropertyAudioonly()
    {
    }

    /**
     * Test attribute "ssl"
     */
    public function testPropertySsl()
    {
    }

    /**
     * Test attribute "parentid"
     */
    public function testPropertyParentid()
    {
    }

    /**
     * Test attribute "server"
     */
    public function testPropertyServer()
    {
    }

    /**
     * Test attribute "backup"
     */
    public function testPropertyBackup()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "ssl_enabled"
     */
    public function testPropertySslEnabled()
    {
    }

    /**
     * Test attribute "playbackurls"
     */
    public function testPropertyPlaybackurls()
    {
    }

    /**
     * Test attribute "url_prefix_no_id"
     */
    public function testPropertyUrlPrefixNoId()
    {
    }

    /**
     * Test attribute "domainlock"
     */
    public function testPropertyDomainlock()
    {
    }

    /**
     * Test attribute "geoblock"
     */
    public function testPropertyGeoblock()
    {
    }

    /**
     * Test attribute "securetoken"
     */
    public function testPropertySecuretoken()
    {
    }

    /**
     * Test attribute "eac"
     */
    public function testPropertyEac()
    {
    }

    /**
     * Test attribute "rtmpauth"
     */
    public function testPropertyRtmpauth()
    {
    }

    /**
     * Test attribute "record"
     */
    public function testPropertyRecord()
    {
    }

    /**
     * Test attribute "preroll"
     */
    public function testPropertyPreroll()
    {
    }

    /**
     * Test attribute "loop"
     */
    public function testPropertyLoop()
    {
    }

    /**
     * Test attribute "has_instant_schedule"
     */
    public function testPropertyHasInstantSchedule()
    {
    }

    /**
     * Test attribute "playlist_count"
     */
    public function testPropertyPlaylistCount()
    {
    }

    /**
     * Test attribute "playlists"
     */
    public function testPropertyPlaylists()
    {
    }

    /**
     * Test attribute "do"
     */
    public function testPropertyDo()
    {
    }

    /**
     * Test attribute "zone"
     */
    public function testPropertyZone()
    {
    }
}
