<?php
/**
 * ZonePullResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ZonePullResultTest Class Doc Comment
 *
 * @category    Class
 * @description ZonePullResult
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ZonePullResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ZonePullResult"
     */
    public function testZonePullResult()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "serviceid"
     */
    public function testPropertyServiceid()
    {
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "cnames"
     */
    public function testPropertyCnames()
    {
    }

    /**
     * Test attribute "live"
     */
    public function testPropertyLive()
    {
    }

    /**
     * Test attribute "wafid"
     */
    public function testPropertyWafid()
    {
    }

    /**
     * Test attribute "edgeruleids"
     */
    public function testPropertyEdgeruleids()
    {
    }

    /**
     * Test attribute "dnscheck"
     */
    public function testPropertyDnscheck()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "customhostheader"
     */
    public function testPropertyCustomhostheader()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "hashid"
     */
    public function testPropertyHashid()
    {
    }

    /**
     * Test attribute "fqdn"
     */
    public function testPropertyFqdn()
    {
    }
}
