<?php
/**
 * PostMultiBitratePush
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PostMultiBitratePush Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PostMultiBitratePush implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PostMultiBitratePush';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        '_method' => 'string',
'name' => 'string',
'server' => 'string',
'audioonly' => 'string',
'profile' => 'string',
'parentid' => 'string',
'ssl' => 'string',
'abr' => '\Swagger\Client\Model\StreamsabrnewAbr',
'domainlock' => '\Swagger\Client\Model\StreamsabrnewDomainlock',
'geoblock' => '\Swagger\Client\Model\StreamsabrnewGeoblock',
'rtmpauth' => '\Swagger\Client\Model\StreamsabrnewRtmpauth',
'eac' => '\Swagger\Client\Model\StreamsabrnewEac'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        '_method' => null,
'name' => null,
'server' => null,
'audioonly' => null,
'profile' => null,
'parentid' => null,
'ssl' => null,
'abr' => null,
'domainlock' => null,
'geoblock' => null,
'rtmpauth' => null,
'eac' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        '_method' => '_METHOD',
'name' => 'name',
'server' => 'server',
'audioonly' => 'audioonly',
'profile' => 'profile[]',
'parentid' => 'parentid',
'ssl' => 'ssl',
'abr' => 'abr',
'domainlock' => 'domainlock',
'geoblock' => 'geoblock',
'rtmpauth' => 'rtmpauth',
'eac' => 'eac'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        '_method' => 'setMethod',
'name' => 'setName',
'server' => 'setServer',
'audioonly' => 'setAudioonly',
'profile' => 'setProfile',
'parentid' => 'setParentid',
'ssl' => 'setSsl',
'abr' => 'setAbr',
'domainlock' => 'setDomainlock',
'geoblock' => 'setGeoblock',
'rtmpauth' => 'setRtmpauth',
'eac' => 'setEac'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        '_method' => 'getMethod',
'name' => 'getName',
'server' => 'getServer',
'audioonly' => 'getAudioonly',
'profile' => 'getProfile',
'parentid' => 'getParentid',
'ssl' => 'getSsl',
'abr' => 'getAbr',
'domainlock' => 'getDomainlock',
'geoblock' => 'getGeoblock',
'rtmpauth' => 'getRtmpauth',
'eac' => 'getEac'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['_method'] = isset($data['_method']) ? $data['_method'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['server'] = isset($data['server']) ? $data['server'] : null;
        $this->container['audioonly'] = isset($data['audioonly']) ? $data['audioonly'] : null;
        $this->container['profile'] = isset($data['profile']) ? $data['profile'] : null;
        $this->container['parentid'] = isset($data['parentid']) ? $data['parentid'] : null;
        $this->container['ssl'] = isset($data['ssl']) ? $data['ssl'] : null;
        $this->container['abr'] = isset($data['abr']) ? $data['abr'] : null;
        $this->container['domainlock'] = isset($data['domainlock']) ? $data['domainlock'] : null;
        $this->container['geoblock'] = isset($data['geoblock']) ? $data['geoblock'] : null;
        $this->container['rtmpauth'] = isset($data['rtmpauth']) ? $data['rtmpauth'] : null;
        $this->container['eac'] = isset($data['eac']) ? $data['eac'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['_method'] === null) {
            $invalidProperties[] = "'_method' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['server'] === null) {
            $invalidProperties[] = "'server' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets _method
     *
     * @return string
     */
    public function getMethod()
    {
        return $this->container['_method'];
    }

    /**
     * Sets _method
     *
     * @param string $_method To cast request method POST to PUT
     *
     * @return $this
     */
    public function setMethod($_method)
    {
        $this->container['_method'] = $_method;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Stream name should be in the format part-1/part-2. <br>Each part should have minimum 3 chars, separated by forward slash ‘/’, without any space.
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets server
     *
     * @return string
     */
    public function getServer()
    {
        return $this->container['server'];
    }

    /**
     * Sets server
     *
     * @param string $server server.code, Should be one of the server code from the GET /streams/abr/servers call
     *
     * @return $this
     */
    public function setServer($server)
    {
        $this->container['server'] = $server;

        return $this;
    }

    /**
     * Gets audioonly
     *
     * @return string
     */
    public function getAudioonly()
    {
        return $this->container['audioonly'];
    }

    /**
     * Sets audioonly
     *
     * @param string $audioonly Values can be Y or N. <br>Set to Y if the HLS audio only stream should be added to the manifest file.
     *
     * @return $this
     */
    public function setAudioonly($audioonly)
    {
        $this->container['audioonly'] = $audioonly;

        return $this;
    }

    /**
     * Gets profile
     *
     * @return string
     */
    public function getProfile()
    {
        return $this->container['profile'];
    }

    /**
     * Sets profile
     *
     * @param string $profile Values can be Y or N. <br>Set to Y if Multiple Encoders should be enabled.<br> Set to N if Multiple Encoders should be disabled.
     *
     * @return $this
     */
    public function setProfile($profile)
    {
        $this->container['profile'] = $profile;

        return $this;
    }

    /**
     * Gets parentid
     *
     * @return string
     */
    public function getParentid()
    {
        return $this->container['parentid'];
    }

    /**
     * Sets parentid
     *
     * @param string $parentid Enter parentid to 1-5
     *
     * @return $this
     */
    public function setParentid($parentid)
    {
        $this->container['parentid'] = $parentid;

        return $this;
    }

    /**
     * Gets ssl
     *
     * @return string
     */
    public function getSsl()
    {
        return $this->container['ssl'];
    }

    /**
     * Sets ssl
     *
     * @param string $ssl Values can be Y or N. <br>Set to Y if HTTPS should be enabled.<br> Set to N if HTTPS should be disabled.
     *
     * @return $this
     */
    public function setSsl($ssl)
    {
        $this->container['ssl'] = $ssl;

        return $this;
    }

    /**
     * Gets abr
     *
     * @return \Swagger\Client\Model\StreamsabrnewAbr
     */
    public function getAbr()
    {
        return $this->container['abr'];
    }

    /**
     * Sets abr
     *
     * @param \Swagger\Client\Model\StreamsabrnewAbr $abr abr
     *
     * @return $this
     */
    public function setAbr($abr)
    {
        $this->container['abr'] = $abr;

        return $this;
    }

    /**
     * Gets domainlock
     *
     * @return \Swagger\Client\Model\StreamsabrnewDomainlock
     */
    public function getDomainlock()
    {
        return $this->container['domainlock'];
    }

    /**
     * Sets domainlock
     *
     * @param \Swagger\Client\Model\StreamsabrnewDomainlock $domainlock domainlock
     *
     * @return $this
     */
    public function setDomainlock($domainlock)
    {
        $this->container['domainlock'] = $domainlock;

        return $this;
    }

    /**
     * Gets geoblock
     *
     * @return \Swagger\Client\Model\StreamsabrnewGeoblock
     */
    public function getGeoblock()
    {
        return $this->container['geoblock'];
    }

    /**
     * Sets geoblock
     *
     * @param \Swagger\Client\Model\StreamsabrnewGeoblock $geoblock geoblock
     *
     * @return $this
     */
    public function setGeoblock($geoblock)
    {
        $this->container['geoblock'] = $geoblock;

        return $this;
    }

    /**
     * Gets rtmpauth
     *
     * @return \Swagger\Client\Model\StreamsabrnewRtmpauth
     */
    public function getRtmpauth()
    {
        return $this->container['rtmpauth'];
    }

    /**
     * Sets rtmpauth
     *
     * @param \Swagger\Client\Model\StreamsabrnewRtmpauth $rtmpauth rtmpauth
     *
     * @return $this
     */
    public function setRtmpauth($rtmpauth)
    {
        $this->container['rtmpauth'] = $rtmpauth;

        return $this;
    }

    /**
     * Gets eac
     *
     * @return \Swagger\Client\Model\StreamsabrnewEac
     */
    public function getEac()
    {
        return $this->container['eac'];
    }

    /**
     * Sets eac
     *
     * @param \Swagger\Client\Model\StreamsabrnewEac $eac eac
     *
     * @return $this
     */
    public function setEac($eac)
    {
        $this->container['eac'] = $eac;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
