<?php
/**
 * ZonePullResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ZonePullResult Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZonePullResult implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'zonePullResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'type' => 'string',
'id' => 'int',
'serviceid' => 'int',
'mode' => 'string',
'origin' => 'string',
'cnames' => 'string',
'live' => 'string',
'wafid' => 'string',
'edgeruleids' => 'int',
'dnscheck' => 'int',
'ip' => 'string',
'customhostheader' => 'string',
'deleted' => 'string',
'name' => 'string',
'hashid' => 'string',
'fqdn' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'type' => null,
'id' => 'int32',
'serviceid' => 'int32',
'mode' => null,
'origin' => null,
'cnames' => null,
'live' => null,
'wafid' => null,
'edgeruleids' => 'int32',
'dnscheck' => 'int32',
'ip' => null,
'customhostheader' => null,
'deleted' => null,
'name' => null,
'hashid' => null,
'fqdn' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
'id' => 'id',
'serviceid' => 'serviceid',
'mode' => 'mode',
'origin' => 'origin',
'cnames' => 'cnames',
'live' => 'live',
'wafid' => 'wafid',
'edgeruleids' => 'edgeruleids',
'dnscheck' => 'dnscheck',
'ip' => 'ip',
'customhostheader' => 'customhostheader',
'deleted' => 'deleted',
'name' => 'name',
'hashid' => 'hashid',
'fqdn' => 'fqdn'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
'id' => 'setId',
'serviceid' => 'setServiceid',
'mode' => 'setMode',
'origin' => 'setOrigin',
'cnames' => 'setCnames',
'live' => 'setLive',
'wafid' => 'setWafid',
'edgeruleids' => 'setEdgeruleids',
'dnscheck' => 'setDnscheck',
'ip' => 'setIp',
'customhostheader' => 'setCustomhostheader',
'deleted' => 'setDeleted',
'name' => 'setName',
'hashid' => 'setHashid',
'fqdn' => 'setFqdn'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
'id' => 'getId',
'serviceid' => 'getServiceid',
'mode' => 'getMode',
'origin' => 'getOrigin',
'cnames' => 'getCnames',
'live' => 'getLive',
'wafid' => 'getWafid',
'edgeruleids' => 'getEdgeruleids',
'dnscheck' => 'getDnscheck',
'ip' => 'getIp',
'customhostheader' => 'getCustomhostheader',
'deleted' => 'getDeleted',
'name' => 'getName',
'hashid' => 'getHashid',
'fqdn' => 'getFqdn'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['serviceid'] = isset($data['serviceid']) ? $data['serviceid'] : null;
        $this->container['mode'] = isset($data['mode']) ? $data['mode'] : null;
        $this->container['origin'] = isset($data['origin']) ? $data['origin'] : null;
        $this->container['cnames'] = isset($data['cnames']) ? $data['cnames'] : null;
        $this->container['live'] = isset($data['live']) ? $data['live'] : null;
        $this->container['wafid'] = isset($data['wafid']) ? $data['wafid'] : null;
        $this->container['edgeruleids'] = isset($data['edgeruleids']) ? $data['edgeruleids'] : null;
        $this->container['dnscheck'] = isset($data['dnscheck']) ? $data['dnscheck'] : null;
        $this->container['ip'] = isset($data['ip']) ? $data['ip'] : null;
        $this->container['customhostheader'] = isset($data['customhostheader']) ? $data['customhostheader'] : null;
        $this->container['deleted'] = isset($data['deleted']) ? $data['deleted'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['hashid'] = isset($data['hashid']) ? $data['hashid'] : null;
        $this->container['fqdn'] = isset($data['fqdn']) ? $data['fqdn'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets serviceid
     *
     * @return int
     */
    public function getServiceid()
    {
        return $this->container['serviceid'];
    }

    /**
     * Sets serviceid
     *
     * @param int $serviceid serviceid
     *
     * @return $this
     */
    public function setServiceid($serviceid)
    {
        $this->container['serviceid'] = $serviceid;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string $mode mode
     *
     * @return $this
     */
    public function setMode($mode)
    {
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets origin
     *
     * @return string
     */
    public function getOrigin()
    {
        return $this->container['origin'];
    }

    /**
     * Sets origin
     *
     * @param string $origin origin
     *
     * @return $this
     */
    public function setOrigin($origin)
    {
        $this->container['origin'] = $origin;

        return $this;
    }

    /**
     * Gets cnames
     *
     * @return string
     */
    public function getCnames()
    {
        return $this->container['cnames'];
    }

    /**
     * Sets cnames
     *
     * @param string $cnames cnames
     *
     * @return $this
     */
    public function setCnames($cnames)
    {
        $this->container['cnames'] = $cnames;

        return $this;
    }

    /**
     * Gets live
     *
     * @return string
     */
    public function getLive()
    {
        return $this->container['live'];
    }

    /**
     * Sets live
     *
     * @param string $live live
     *
     * @return $this
     */
    public function setLive($live)
    {
        $this->container['live'] = $live;

        return $this;
    }

    /**
     * Gets wafid
     *
     * @return string
     */
    public function getWafid()
    {
        return $this->container['wafid'];
    }

    /**
     * Sets wafid
     *
     * @param string $wafid wafid
     *
     * @return $this
     */
    public function setWafid($wafid)
    {
        $this->container['wafid'] = $wafid;

        return $this;
    }

    /**
     * Gets edgeruleids
     *
     * @return int
     */
    public function getEdgeruleids()
    {
        return $this->container['edgeruleids'];
    }

    /**
     * Sets edgeruleids
     *
     * @param int $edgeruleids edgeruleids
     *
     * @return $this
     */
    public function setEdgeruleids($edgeruleids)
    {
        $this->container['edgeruleids'] = $edgeruleids;

        return $this;
    }

    /**
     * Gets dnscheck
     *
     * @return int
     */
    public function getDnscheck()
    {
        return $this->container['dnscheck'];
    }

    /**
     * Sets dnscheck
     *
     * @param int $dnscheck dnscheck
     *
     * @return $this
     */
    public function setDnscheck($dnscheck)
    {
        $this->container['dnscheck'] = $dnscheck;

        return $this;
    }

    /**
     * Gets ip
     *
     * @return string
     */
    public function getIp()
    {
        return $this->container['ip'];
    }

    /**
     * Sets ip
     *
     * @param string $ip ip
     *
     * @return $this
     */
    public function setIp($ip)
    {
        $this->container['ip'] = $ip;

        return $this;
    }

    /**
     * Gets customhostheader
     *
     * @return string
     */
    public function getCustomhostheader()
    {
        return $this->container['customhostheader'];
    }

    /**
     * Sets customhostheader
     *
     * @param string $customhostheader customhostheader
     *
     * @return $this
     */
    public function setCustomhostheader($customhostheader)
    {
        $this->container['customhostheader'] = $customhostheader;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return string
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param string $deleted deleted
     *
     * @return $this
     */
    public function setDeleted($deleted)
    {
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets hashid
     *
     * @return string
     */
    public function getHashid()
    {
        return $this->container['hashid'];
    }

    /**
     * Sets hashid
     *
     * @param string $hashid hashid
     *
     * @return $this
     */
    public function setHashid($hashid)
    {
        $this->container['hashid'] = $hashid;

        return $this;
    }

    /**
     * Gets fqdn
     *
     * @return string
     */
    public function getFqdn()
    {
        return $this->container['fqdn'];
    }

    /**
     * Sets fqdn
     *
     * @param string $fqdn fqdn
     *
     * @return $this
     */
    public function setFqdn($fqdn)
    {
        $this->container['fqdn'] = $fqdn;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
