<?php
/**
 * DvrStreamApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DvrStreamApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DvrStreamApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for dvrStreamlist
     *
     * DvrStream.
     *
     */
    public function testDvrStreamlist()
    {
    }

    /**
     * Test case for getDetailsDvrStream
     *
     * DvrStream.
     *
     */
    public function testGetDetailsDvrStream()
    {
    }

    /**
     * Test case for restartDvrStream
     *
     * Restart.
     *
     */
    public function testRestartDvrStream()
    {
    }

    /**
     * Test case for restore8
     *
     * Restore.
     *
     */
    public function testRestore8()
    {
    }

    /**
     * Test case for updateDomainlockDvrStream
     *
     * Update Domain Lock.
     *
     */
    public function testUpdateDomainlockDvrStream()
    {
    }

    /**
     * Test case for updateExternalAuthControlDvrStream
     *
     * Update External Auth Control.
     *
     */
    public function testUpdateExternalAuthControlDvrStream()
    {
    }

    /**
     * Test case for updateGeoblockStreamsRecord
     *
     * Update Geo Block.
     *
     */
    public function testUpdateGeoblockStreamsRecord()
    {
    }

    /**
     * Test case for updateInfoDvrStream
     *
     * DvrStream.
     *
     */
    public function testUpdateInfoDvrStream()
    {
    }

    /**
     * Test case for updateSecureTokenStreamsRecord
     *
     * Update Secure Token.
     *
     */
    public function testUpdateSecureTokenStreamsRecord()
    {
    }
}
