<?php
/**
 * ScheduledplaylistApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ScheduledplaylistApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScheduledplaylistApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createPlaylistScheduledPlaylist
     *
     * Create Playlist.
     *
     */
    public function testCreatePlaylistScheduledPlaylist()
    {
    }

    /**
     * Test case for createScheduledPlaylist
     *
     * Create Scheduled Playlist.
     *
     */
    public function testCreateScheduledPlaylist()
    {
    }

    /**
     * Test case for getDetailsScheduledPlaylist
     *
     * Stream.
     *
     */
    public function testGetDetailsScheduledPlaylist()
    {
    }

    /**
     * Test case for restartScheduledPlaylist
     *
     * Restart.
     *
     */
    public function testRestartScheduledPlaylist()
    {
    }

    /**
     * Test case for restoreScheduledPlaylist
     *
     * Restore.
     *
     */
    public function testRestoreScheduledPlaylist()
    {
    }

    /**
     * Test case for scheduledPlayList
     *
     * Stream.
     *
     */
    public function testScheduledPlayList()
    {
    }

    /**
     * Test case for updateDomainlockScheduledPlaylist
     *
     * Update Domain Lock.
     *
     */
    public function testUpdateDomainlockScheduledPlaylist()
    {
    }

    /**
     * Test case for updateExternalAuthControlScheduledPlaylist
     *
     * Update External Auth Control.
     *
     */
    public function testUpdateExternalAuthControlScheduledPlaylist()
    {
    }

    /**
     * Test case for updateGeoblockScheduledPlaylist
     *
     * Update Geo Block.
     *
     */
    public function testUpdateGeoblockScheduledPlaylist()
    {
    }

    /**
     * Test case for updateInfoScheduledPlaylist
     *
     * Update Info.
     *
     */
    public function testUpdateInfoScheduledPlaylist()
    {
    }

    /**
     * Test case for updatePlaylistScheduledPlaylist
     *
     * Update Playlist.
     *
     */
    public function testUpdatePlaylistScheduledPlaylist()
    {
    }

    /**
     * Test case for updateRtmpauthScheduledPlaylist
     *
     * Update RTMPAuth.
     *
     */
    public function testUpdateRtmpauthScheduledPlaylist()
    {
    }

    /**
     * Test case for updateSecureTokenScheduledPlaylist
     *
     * Update Secure Token.
     *
     */
    public function testUpdateSecureTokenScheduledPlaylist()
    {
    }
}
