<?php
/**
 * StreamreportApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * StreamreportApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StreamreportApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for byBrowserReport
     *
     * By Browser report.
     *
     */
    public function testByBrowserReport()
    {
    }

    /**
     * Test case for byCountryReport
     *
     * By Country report.
     *
     */
    public function testByCountryReport()
    {
    }

    /**
     * Test case for byOsReport
     *
     * By OS report.
     *
     */
    public function testByOsReport()
    {
    }

    /**
     * Test case for cacheStatisticsReport
     *
     * streamreport.
     *
     */
    public function testCacheStatisticsReport()
    {
    }

    /**
     * Test case for statusCodesReport
     *
     * Status Codes report.
     *
     */
    public function testStatusCodesReport()
    {
    }

    /**
     * Test case for summaryReport
     *
     * streamreport.
     *
     */
    public function testSummaryReport()
    {
    }

    /**
     * Test case for topFilesReport
     *
     * Top Files report.
     *
     */
    public function testTopFilesReport()
    {
    }

    /**
     * Test case for topReferrersReport
     *
     * Top Referrers report.
     *
     */
    public function testTopReferrersReport()
    {
    }

    /**
     * Test case for visitorsReport
     *
     * Visitors report.
     *
     */
    public function testVisitorsReport()
    {
    }
}
