<?php
/**
 * ZonevodpullreportApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ZonevodpullreportApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZonevodpullreportApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for reportsByZoneVodPullBrowsers
     *
     * Reports by zone vod pull browsers.
     *
     */
    public function testReportsByZoneVodPullBrowsers()
    {
    }

    /**
     * Test case for reportsByZoneVodPullCache
     *
     * Reports by zone vod pull cache.
     *
     */
    public function testReportsByZoneVodPullCache()
    {
    }

    /**
     * Test case for reportsByZoneVodPullCountries
     *
     * Reports by zone vod pull countries.
     *
     */
    public function testReportsByZoneVodPullCountries()
    {
    }

    /**
     * Test case for reportsByZoneVodPullOs
     *
     * Reports by zone vod pull os.
     *
     */
    public function testReportsByZoneVodPullOs()
    {
    }

    /**
     * Test case for reportsByZoneVodPullStatuscodes
     *
     * Reports by zone vod push statuscodes.
     *
     */
    public function testReportsByZoneVodPullStatuscodes()
    {
    }

    /**
     * Test case for reportsByZoneVodPullSummary
     *
     * Reports by zone vod pull summary.
     *
     */
    public function testReportsByZoneVodPullSummary()
    {
    }

    /**
     * Test case for reportsByZoneVodPullTopfiles
     *
     * Reports by zone vod pull topfiles.
     *
     */
    public function testReportsByZoneVodPullTopfiles()
    {
    }

    /**
     * Test case for reportsByZoneVodPullTopreferrers
     *
     * Reports by zone vod pull topreferrers.
     *
     */
    public function testReportsByZoneVodPullTopreferrers()
    {
    }

    /**
     * Test case for reportsByZoneVodPullVisitors
     *
     * Reports by zone vod pull visitors.
     *
     */
    public function testReportsByZoneVodPullVisitors()
    {
    }
}
