<?php
/**
 * ZonepullApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ZonepullApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZonepullApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createZonePull
     *
     * Create Zone.
     *
     */
    public function testCreateZonePull()
    {
    }

    /**
     * Test case for getZonePull
     *
     * Zone.
     *
     */
    public function testGetZonePull()
    {
    }

    /**
     * Test case for restoreZonePull
     *
     * Restore.
     *
     */
    public function testRestoreZonePull()
    {
    }

    /**
     * Test case for updateCacheZonePull
     *
     * Update Cache.
     *
     */
    public function testUpdateCacheZonePull()
    {
    }

    /**
     * Test case for updateDomainLockZonePull
     *
     * Update Domain Lock.
     *
     */
    public function testUpdateDomainLockZonePull()
    {
    }

    /**
     * Test case for updateEdgeSettingsZonePull
     *
     * Update Edge Settings.
     *
     */
    public function testUpdateEdgeSettingsZonePull()
    {
    }

    /**
     * Test case for updateSecureTokenZonePull
     *
     * Update Secure Token.
     *
     */
    public function testUpdateSecureTokenZonePull()
    {
    }

    /**
     * Test case for updateSslZonePull
     *
     * Update SSL.
     *
     */
    public function testUpdateSslZonePull()
    {
    }

    /**
     * Test case for updateZonePull
     *
     * Update Info.
     *
     */
    public function testUpdateZonePull()
    {
    }

    /**
     * Test case for zoneCachePurgeZonePull
     *
     * Purge.
     *
     */
    public function testZoneCachePurgeZonePull()
    {
    }

    /**
     * Test case for zonePullList
     *
     * Zone.
     *
     */
    public function testZonePullList()
    {
    }
}
