<?php
/**
 * ZonepushreportApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 5centscdn API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ZonepushreportApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZonepushreportApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for reportsByZonePushBrowsers
     *
     * Reports by zone push browsers.
     *
     */
    public function testReportsByZonePushBrowsers()
    {
    }

    /**
     * Test case for reportsByZonePushCache
     *
     * Reports by zone push  Cache Statistics.
     *
     */
    public function testReportsByZonePushCache()
    {
    }

    /**
     * Test case for reportsByZonePushCountries
     *
     * Reports by zone push countries.
     *
     */
    public function testReportsByZonePushCountries()
    {
    }

    /**
     * Test case for reportsByZonePushOs
     *
     * Reports by zone push os.
     *
     */
    public function testReportsByZonePushOs()
    {
    }

    /**
     * Test case for reportsByZonePushStatusCode
     *
     * Reports by zone push Status Codes.
     *
     */
    public function testReportsByZonePushStatusCode()
    {
    }

    /**
     * Test case for reportsByZonePushSummary
     *
     * Reports by zone push Summary.
     *
     */
    public function testReportsByZonePushSummary()
    {
    }

    /**
     * Test case for reportsByZonePushTopFiles
     *
     * Reports by zone push Top Files.
     *
     */
    public function testReportsByZonePushTopFiles()
    {
    }

    /**
     * Test case for reportsByZonePushTopReferrers
     *
     * Reports by zone push Top Referrers.
     *
     */
    public function testReportsByZonePushTopReferrers()
    {
    }

    /**
     * Test case for reportsByZonePushVisitors
     *
     * Reports by zone push visitors.
     *
     */
    public function testReportsByZonePushVisitors()
    {
    }
}
